export enum Attributes {
  alignment = 'alignment' ,
  type = 'type' ,
  size = 'size' ,
  armor_tag = 'armor_tag' ,
  speeds = 'speeds' ,
  immunities = 'immunities_damage' ,
  resists = 'resists_damage' ,
  vulnerabilities = 'vulnerabilities_damage' ,
  feelings = 'feelings' ,
  saving_throws = 'saving_throws' ,
  skills = 'skills' ,
  conditions = 'conditions',
  languages= 'languages',
  regions = 'regions',
}
